/**
 * remediationSpecGenerator.js — Actionable Codebase Audit & LLM Remediation Spec Generator
 *
 * Generates an exhaustive, high-density Markdown document structured specifically
 * for developers to prioritize technical debt and for LLMs (Claude, Cursor, Copilot, ChatGPT)
 * to immediately generate production-ready refactorings and code patches without ambiguity.
 */

export function generateRemediationSpec(result = {}, options = {}) {
  const {
    metrics = {},
    requirements = { dependencies: [], commands: [] },
    scorecard = { grade: 'A+', score: 100, breakdown: {}, recommendations: [] },
    pythonAnalysis = {},
    jsSecurityIssues = [],
    complexityReport = { byFile: [], highComplexityCount: 0 },
    jsCircularDeps = [],
    commentRatios = { perFile: [], poorlyDocumented: [], avgRatio: 0 },
    largeFiles = [],
    couplingData = { couplingMap: [], highlyCoupledCount: 0 },
    deadCode = { totalUnusedExports: 0, unusedExports: [], totalOrphanFiles: 0, orphanFiles: [] },
    duplication = { duplicationPercentage: 0, duplicateBlocks: [] },
    licenseAudit = { copyleftCount: 0, copyleftPackages: [] },
    technicalDebt = { totalCount: 0, items: [], byTag: {}, highSeverityCount: 0 },
    apiDrift = { driftScore: 100, danglingCalls: [], orphanRoutes: [], matchedContracts: [] },
  } = result;

  const projectName = options.projectName || 'Codebase';
  const timestamp = new Date().toISOString();
  const humanDate = new Date().toLocaleString();

  // Merge security issues
  const pySec = pythonAnalysis.securityIssues || [];
  const allSecurityIssues = [...pySec, ...jsSecurityIssues];

  // Merge circular dependencies
  const pyCirc = pythonAnalysis.circularDependencies || [];
  const allCircularDeps = [...pyCirc, ...jsCircularDeps];

  // Hotspots
  const hotspots = pythonAnalysis.hotspots || [];

  const lines = [];

  // ─────────────────────────────────────────────
  // 1. EXECUTIVE HEADER
  // ─────────────────────────────────────────────
  lines.push(`# 🛠️ CODEBASE REFACTORING SPECIFICATION & AUDIT`);
  lines.push(`> **Project**: \`${projectName}\` | **Generated by**: CodeScanner Static Engine`);
  lines.push(`> **Audit Date**: ${humanDate} (\`${timestamp}\`)`);
  lines.push(`> **Overall Health Grade**: **${scorecard.grade || 'A+'}** (**${scorecard.score || 100}/100**)`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 2. MASTER OBJECTIVE FOR DEVELOPER / LLM
  // ─────────────────────────────────────────────
  lines.push('## 🎯 OBJECTIVE FOR DEVELOPER & AI CODE ASSISTANT');
  lines.push('You are acting as a **Principal Software Architect and Security Auditor**.');
  lines.push('Your mission is to systematically resolve the architectural defects, security vulnerabilities, and code quality hotspots detailed below.');
  lines.push('');
  lines.push('### Strict Execution Rules:');
  lines.push('1. **Priority Order**: Address issues strictly in order from **P0 (Critical Security)** down to **P5 (Documentation & Cleanliness)**.');
  lines.push('2. **Preserve API Contracts**: Do not break existing public exported function signatures, route contracts, or data schemas unless explicitly instructed.');
  lines.push('3. **Zero Regression**: Ensure all imports in downstream dependent files (see Blast Radius notes) are properly updated when renaming or moving modules.');
  lines.push('4. **Minimal Blast Radius**: When refactoring God Files or breaking Circular Dependencies, extract leaf utility modules with no back-references.');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 3. CODEBASE SNAPSHOT METRICS
  // ─────────────────────────────────────────────
  lines.push('## 📊 CODEBASE METRICS SUMMARY');
  lines.push(`- **Total Source Files**: \`${(metrics.totalFiles || 0).toLocaleString()}\``);
  lines.push(`- **Total Lines of Code (LOC)**: \`${(metrics.totalLines || 0).toLocaleString()}\``);
  lines.push(`- **Primary Language**: \`${metrics.primaryLanguage || 'Unknown'}\``);
  if (metrics.byLanguage && Object.keys(metrics.byLanguage).length > 0) {
    const langList = Object.entries(metrics.byLanguage)
      .map(([lang, count]) => `${lang} (${count} files)`)
      .join(', ');
    lines.push(`- **Language Breakdown**: ${langList}`);
  }
  lines.push(`- **Documentation Ratio**: \`${commentRatios.avgRatio || 0}%\` average comment density across codebase`);
  lines.push(`- **Duplication Density**: \`${duplication.duplicationPercentage || 0}%\` duplicate blocks detected`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 4. PRIORITY 0: SECURITY & SECRET VULNERABILITIES
  // ─────────────────────────────────────────────
  lines.push('## 🚨 [P0] CRITICAL SECURITY VULNERABILITIES & SECRET LEAKS');
  lines.push('All issues in this section represent immediate security liabilities (CWE violations or secret leakage) and must be remediated first.');
  lines.push('');

  if (allSecurityIssues.length === 0) {
    lines.push('✅ **No static security vulnerabilities or leaked secrets detected.**');
  } else {
    allSecurityIssues.forEach((sec, idx) => {
      lines.push(`### Issue P0-${idx + 1}: ${sec.rule || 'Security Finding'}`);
      lines.push(`- **Severity**: \`${(sec.severity || 'High').toUpperCase()}\``);
      lines.push(`- **Target File**: \`${sec.file}\` (approx. line ${sec.line || 1})`);
      if (sec.snippet) {
        lines.push(`- **Vulnerable Code Snippet**:`);
        lines.push('  ```');
        lines.push(`  ${sec.snippet}`);
        lines.push('  ```');
      }
      lines.push(`- **Root Cause & Risk**: Hardcoded credentials, insecure deserialization, direct HTML injection, or unsafe process execution allows unauthorized access or code execution.`);
      lines.push(`- **Step-by-Step Remediation Plan**:`);
      lines.push(`  1. Extract hardcoded secrets into environment variables (e.g. \`process.env.VAR\` or \`os.getenv('VAR')\`).`);
      lines.push(`  2. Add dummy entry to \`.env.example\` and verify \`.env\` is included in \`.gitignore\`.`);
      lines.push(`  3. If unsafe dynamic execution (\`eval\`, \`subprocess.call(shell=True)\`, \`pickle.loads\`) is used, replace with safe alternatives (\`JSON.parse\`, parameterized argument array, or cryptographic verification).`);
      lines.push('');
    });
  }

  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 5. PRIORITY 1: CIRCULAR DEPENDENCIES
  // ─────────────────────────────────────────────
  lines.push('## 🔄 [P1] ARCHITECTURAL CIRCULAR DEPENDENCIES');
  lines.push('Circular import cycles prevent tree-shaking, leak memory, cause runtime initialization deadlocks (`undefined` imported values), and impede unit testing.');
  lines.push('');

  if (allCircularDeps.length === 0) {
    lines.push('✅ **No circular dependency cycles detected across the project dependency graph.**');
  } else {
    allCircularDeps.forEach((cycle, idx) => {
      const chainStr = cycle.summary || (cycle.chain ? cycle.chain.join(' ➔ ') : 'Circular cycle');
      lines.push(`### Cycle P1-${idx + 1}: ${chainStr}`);
      lines.push(`- **Severity**: \`${(cycle.severity || 'High').toUpperCase()}\` (${cycle.length || cycle.chain?.length || 2} modules in cycle)`);
      if (cycle.fullPaths && cycle.fullPaths.length > 0) {
        lines.push(`- **Full Path Sequence**:`);
        cycle.fullPaths.forEach((fp, i) => lines.push(`  ${i + 1}. \`${fp}\``));
      }
      lines.push(`- **Decoupling Strategy**:`);
      lines.push(`  1. Identify shared utilities, types, or configuration constants causing mutual imports.`);
      lines.push(`  2. Extract shared definitions into a new leaf module (e.g. \`types.ts\`, \`constants.ts\`, or \`sharedHelpers.ts\`).`);
      lines.push(`  3. Update both sides of the cycle to import from the leaf module without importing each other.`);
      lines.push('');
    });
  }

  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 6. PRIORITY 2: GOD FILES & REFACTORING HOTSPOTS
  // ─────────────────────────────────────────────
  lines.push('## 🧱 [P2] GOD FILES & ARCHITECTURAL REFACTORING HOTSPOTS');
  lines.push('God files (>350 LOC) violate the Single Responsibility Principle (SRP) and represent high-friction refactoring bottlenecks.');
  lines.push('');

  const godFilesList = largeFiles.length > 0 ? largeFiles : hotspots;

  if (godFilesList.length === 0) {
    lines.push('✅ **No oversized God Files exceeding recommended length thresholds.**');
  } else {
    godFilesList.forEach((fileItem, idx) => {
      const fname = fileItem.file || fileItem.name || 'Unknown File';
      const loc = fileItem.loc || fileItem.lines || 0;
      const severity = fileItem.severity || fileItem.priority || 'Moderate';
      const coupling = couplingData.couplingMap?.find(c => c.file === fname);

      lines.push(`### Module P2-${idx + 1}: \`${fname}\` (${loc.toLocaleString()} LOC)`);
      lines.push(`- **Severity Rating**: \`${severity.toUpperCase()}\``);
      if (coupling) {
        lines.push(`- **Coupling Degree**: \`${coupling.outDegree}\` imports (out-degree) | \`${coupling.inDegree}\` dependents (in-degree)`);
      }
      lines.push(`- **Architectural Warning**: ${fileItem.warning || fileItem.recommendation || 'Exceeds recommended 350-line boundary.'}`);
      lines.push(`- **Decomposition Blueprint**:`);
      lines.push(`  1. **Extract State Logic**: Move state management, hooks, and lifecycle handlers into dedicated custom hooks (\`use${fileItem.shortName?.replace(/\.[^.]+$/, '') || 'Data'}.ts\`).`);
      lines.push(`  2. **Extract Pure Utilities**: Move formatting, transformation, and validation algorithms into pure stateless helper functions.`);
      lines.push(`  3. **Modularize Presentation**: Break down child panels or sub-views into separate focused component files.`);
      lines.push('');
    });
  }

  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 7. PRIORITY 3: DEAD CODE & ORPHAN MODULES
  // ─────────────────────────────────────────────
  lines.push('## 🗑️ [P3] DEAD CODE & ORPHAN MODULES');
  lines.push('Unused exports and unreachable files increase bundle size, clutter imports, and mislead developers.');
  lines.push('');

  const unusedExports = deadCode.unusedExports || [];
  const orphanFiles = deadCode.orphanFiles || [];

  if (unusedExports.length === 0 && orphanFiles.length === 0) {
    lines.push('✅ **No dead exports or orphan source files detected.**');
  } else {
    if (orphanFiles.length > 0) {
      lines.push(`### Orphan Files (${orphanFiles.length} detected):`);
      lines.push('These files are never imported anywhere in the project graph:');
      orphanFiles.slice(0, 15).forEach(f => lines.push(`- \`${f}\``));
      lines.push('*(Action: Verify if these are obsolete tests, dead prototypes, or if they should be wired into entry points; delete if obsolete.)*');
      lines.push('');
    }
    if (unusedExports.length > 0) {
      lines.push(`### Unused Exported Symbols (${unusedExports.length} detected):`);
      unusedExports.slice(0, 20).forEach(u => {
        lines.push(`- \`${u.symbol}\` in \`${u.file}\``);
      });
      lines.push('*(Action: Remove `export` modifier to scope locally or delete if never used.)*');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 7.5. API CONTRACT DRIFT
  // ─────────────────────────────────────────────
  lines.push('## 🔌 [P3.5] FULL-STACK API CONTRACT DRIFT');
  lines.push(`Contract Alignment Score: **${apiDrift.driftScore ?? 100}%**`);
  lines.push('');

  const dangling = apiDrift.danglingCalls || [];
  if (dangling.length > 0) {
    lines.push(`### ⚠️ Dangling Client API Calls (${dangling.length} unimplemented endpoints):`);
    lines.push('The frontend calls these endpoints, but no matching backend route was discovered:');
    dangling.forEach(d => {
      lines.push(`- \`${d.method || 'GET'} ${d.endpoint}\` called in \`${d.file}:${d.line || 1}\``);
    });
    lines.push('*(Action: Implement the missing server endpoint handlers or remove dead frontend client requests.)*');
    lines.push('');
  } else {
    lines.push('✅ **No dangling client API calls. All client requests map to backend endpoints.**');
    lines.push('');
  }

  // ─────────────────────────────────────────────
  // 7.6. TECHNICAL DEBT & ANNOTATIONS
  // ─────────────────────────────────────────────
  lines.push('## ⏳ [P3.6] TECHNICAL DEBT & UNRESOLVED ANNOTATIONS');
  lines.push(`Total Annotations: \`${technicalDebt.totalCount || 0}\` (\`${technicalDebt.highSeverityCount || 0}\` urgent fixes)`);
  lines.push('');

  const debtItems = technicalDebt.items || [];
  if (debtItems.length > 0) {
    const urgentDebt = debtItems.filter(i => i.severity === 'High');
    if (urgentDebt.length > 0) {
      lines.push(`### Urgent Fixes (FIXME / HACK / BUG / XXX - ${urgentDebt.length} items):`);
      urgentDebt.slice(0, 15).forEach(u => {
        lines.push(`- **\`${u.tag}\`** in \`${u.file}:${u.line}\`: ${u.message}${u.author ? ` (@${u.author})` : ''}`);
      });
      lines.push('');
    }

    const todoItems = debtItems.filter(i => i.tag === 'TODO');
    if (todoItems.length > 0) {
      lines.push(`### Pending TODOs (${todoItems.length} items):`);
      todoItems.slice(0, 10).forEach(t => {
        lines.push(`- \`${t.file}:${t.line}\`: ${t.message}`);
      });
      lines.push('');
    }
  } else {
    lines.push('✅ **No unresolved TODO or FIXME comment flags found.**');
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 8. PRIORITY 4: CODE DUPLICATION & LICENSE AUDIT
  // ─────────────────────────────────────────────
  lines.push('## 👯 [P4] CODE DUPLICATION & LICENSE COMPLIANCE');
  lines.push('');

  if (duplication.duplicationPercentage > 3) {
    lines.push(`### Code Duplication (${duplication.duplicationPercentage}% of codebase):`);
    lines.push(`- Duplicate logic was detected across multiple modules.`);
    lines.push(`- **Action**: Extract duplicated algorithms or schemas into a single shared utility function.`);
  } else {
    lines.push('✅ **Duplication levels are well within healthy boundaries (<3%).**');
  }
  lines.push('');

  if (licenseAudit.copyleftCount > 0) {
    lines.push(`### ⚠️ Copyleft License Compliance Alert (${licenseAudit.copyleftCount} dependencies):`);
    lines.push(`- The following packages carry viral Copyleft licenses (GPL/AGPL) which may require open-sourcing proprietary application code:`);
    (licenseAudit.copyleftPackages || []).forEach(pkg => lines.push(`  - \`${pkg.name}\` (\`${pkg.license}\`)`));
    lines.push(`- **Action**: Audit licenses or replace with MIT/Apache-2.0 alternatives.`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 9. PRIORITY 5: CYCLOMATIC COMPLEXITY & DOCUMENTATION
  // ─────────────────────────────────────────────
  lines.push('## 🧠 [P5] CYCLOMATIC COMPLEXITY & DOCUMENTATION DENSITY');
  lines.push('');

  const highComplexityFiles = complexityReport.byFile?.filter(f => f.severity === 'Critical' || f.severity === 'High') || [];
  if (highComplexityFiles.length > 0) {
    lines.push(`### High Cyclomatic Complexity Files (${highComplexityFiles.length} files):`);
    highComplexityFiles.forEach(f => {
      lines.push(`- **\`${f.file}\`**: Complexity Score \`${f.complexity}\` (${f.severity} branching density)`);
      if (f.breakdown) {
        const topTriggers = Object.entries(f.breakdown)
          .filter(([, v]) => v > 0)
          .map(([k, v]) => `${k}: ${v}`)
          .join(', ');
        lines.push(`  - Trigger breakdown: ${topTriggers}`);
      }
    });
    lines.push('*(Action: Flatten nested conditionals using guard clauses, early returns, and lookup tables.)*');
    lines.push('');
  }

  const poorlyDoc = commentRatios.poorlyDocumented || [];
  if (poorlyDoc.length > 0) {
    lines.push(`### Undocumented Modules (<5% comment density):`);
    lines.push(`Total poorly documented modules: \`${poorlyDoc.length}\`. Key files needing JSDoc / docstrings:`);
    poorlyDoc.slice(0, 10).forEach(f => lines.push(`- \`${f.file}\` (${f.commentRatio}% comment ratio)`));
    lines.push('*(Action: Add clear header docstrings explaining the module’s single responsibility and input/output contracts.)*');
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ─────────────────────────────────────────────
  // 10. COPY-PASTE READY LLM PROMPT BLOCK
  // ─────────────────────────────────────────────
  lines.push('## 🤖 READY-TO-USE PROMPT FOR AI CODE ASSISTANTS (CURSOR / CLAUDE / COPILOT)');
  lines.push('You can copy the prompt below directly into your AI chat to begin automated refactoring:');
  lines.push('');
  lines.push('```text');
  lines.push('I need you to act as a Principal Software Engineer and refactor my repository according to this static analysis report.');
  lines.push(`Project: ${projectName} | Current Health Score: ${scorecard.score || 100}/100 (Grade ${scorecard.grade || 'A+'})`);
  lines.push('');
  lines.push('Please follow these instructions:');
  lines.push('1. Review [P0] Critical Security Vulnerabilities and propose the exact, minimal diff to eliminate hardcoded secrets and unsafe execution.');
  lines.push('2. Review [P1] Circular Dependencies and show the code for an extracted leaf module that breaks the cycle without altering external imports.');
  lines.push('3. Review [P2] God Files and propose a decomposition structure splitting the file into a main container + custom hooks/services.');
  lines.push('4. Produce clean, idiomatic code adhering to TypeScript/ESM/PEP-8 standards with zero breaking changes.');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generates an isolated, pinpoint prompt tailored for a single issue.
 */
export function generateSingleIssuePrompt(type, data = {}, context = {}) {
  switch (type) {
    case 'security':
      return [
        `Fix this security vulnerability in my codebase:`,
        `- File: ${data.file}:${data.line || 1}`,
        `- Vulnerability Rule: ${data.rule}`,
        `- Severity: ${data.severity}`,
        data.snippet ? `- Matched Code: "${data.snippet}"` : '',
        `Task: Provide the secure replacement code using environment variables or safe APIs. Do not break dependent files.`
      ].filter(Boolean).join('\n');

    case 'god_file':
      return [
        `Decompose and refactor this God File:`,
        `- File: ${data.file}`,
        `- Length: ${data.loc || 0} lines of code`,
        `- Severity: ${data.severity || 'High'}`,
        `- Warning: ${data.warning || 'Exceeds recommended 350-line boundary.'}`,
        `Task: Split this module into 1) A clean parent component/module, 2) Dedicated custom hook or helper service, and 3) Isolated presentation sub-components. Provide the refactored code structure.`
      ].join('\n');

    case 'circular_dep':
      return [
        `Break this circular dependency cycle in my codebase:`,
        `- Dependency Chain: ${data.summary || data.chain?.join(' -> ')}`,
        `- Severity: ${data.severity || 'High'}`,
        `Task: Explain how to decouple these modules by extracting shared types, constants, or utility functions into a third leaf file. Provide the exact file structure and refactored import statements.`
      ].join('\n');

    case 'complexity':
      return [
        `Refactor this high-complexity function/file to improve maintainability:`,
        `- File: ${data.file}`,
        `- Cyclomatic Complexity Score: ${data.complexity}`,
        `- Severity: ${data.severity || 'High'}`,
        `Task: Simplify branching logic using guard clauses, early returns, strategy dictionaries, or helper sub-functions. Provide the refactored code.`
      ].join('\n');

    case 'debt':
      return [
        `Resolve this ${data.tag || 'TODO'} comment in my codebase:`,
        `- File: ${data.file}:${data.line || 1}`,
        `- Annotation: ${data.tag}${data.author ? ` (@${data.author})` : ''}`,
        `- Message: "${data.message}"`,
        `Task: Provide the permanent implementation or fix to address this comment and remove the technical debt annotation.`
      ].join('\n');

    case 'api_drift':
      return [
        `Implement missing backend API endpoint for this dangling client call:`,
        `- Client File: ${data.file}:${data.line || 1}`,
        `- HTTP Method: ${data.method || 'GET'}`,
        `- Endpoint Path: ${data.endpoint}`,
        `Task: Create the backend route handler with input validation, appropriate status codes, and JSON response structure matching standard REST conventions.`
      ].join('\n');

    default:
      return `Please review and refactor ${data.file || 'this module'} to address code quality and architectural health issues.`;
  }
}
