// src/components/dashboard/DownloadButton.jsx
import React, { useState } from 'react';
import { Download, FileCode, FileText, Code2, ChevronDown, Sparkles, Bot } from 'lucide-react';
import { generateRemediationSpec } from '../../utils/remediationSpecGenerator';

export default function DownloadButton({ result, projectName = 'codebase', onOpenRemediationModal }) {
  const [open, setOpen] = useState(false);
  if (!result) return null;

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type: `${type};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setOpen(false);
  };

  const handleDownloadRemediationSpec = () => {
    const content = generateRemediationSpec(result, { projectName });
    downloadFile(content, `${projectName}-REFACTOR_SPEC.md`, 'text/markdown');
  };

  const handleDownloadMd = () => {
    const { metrics = {}, requirements = { commands: [], dependencies: [] }, hld = '', lld = '', lineage = '', scorecard = {} } = result;
    const now = new Date().toLocaleString();

    const lines = [
      `# Codebase Analysis & Health Report`,
      `> Generated by CodeScanner on ${now}`,
      `> **Overall Grade**: ${scorecard.grade || 'A+'} (${scorecard.score || 100}/100)`,
      '',
      '---',
      '',
      '## 📊 Metrics Summary',
      `- **Total Files**: ${(metrics.totalFiles || 0).toLocaleString()}`,
      `- **Total Lines of Code**: ${(metrics.totalLines || 0).toLocaleString()}`,
      `- **Languages**: ${Object.keys(metrics.byLanguage || {}).join(', ')}`,
      '',
      '---',
      '## 🏗 Architecture Diagrams',
      '### High-Level Design (HLD)',
      '```mermaid',
      hld,
      '```',
      '### Low-Level Design (LLD)',
      '```mermaid',
      lld,
      '```',
      '### Lineage Graph',
      '```mermaid',
      lineage,
      '```',
    ];

    downloadFile(lines.join('\n'), `${projectName}-audit-report.md`, 'text/markdown');
  };

  const handleDownloadHtml = () => {
    const { metrics = {}, scorecard = {} } = result;
    const now = new Date().toLocaleString();

    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>CodeScanner Report - ${projectName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0a0a0f; color: #f8fafc; padding: 40px; max-width: 900px; margin: 0 auto; }
    h1 { color: #a855f7; border-bottom: 1px solid #1e293b; padding-bottom: 10px; }
    .card { background: #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 20px; border: 1px solid #334155; }
    .grade { font-size: 48px; font-weight: 900; color: #10b981; }
    .stat { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #334155; }
  </style>
</head>
<body>
  <h1>⚡ CodeScanner Executive Report</h1>
  <p style="color: #94a3b8">Project: <strong>${projectName}</strong> | Generated: ${now}</p>

  <div class="card">
    <h2>Architecture Grade</h2>
    <div class="grade">${scorecard.grade || 'A+'} (${scorecard.score || 100}/100)</div>
  </div>

  <div class="card">
    <h2>Metrics Overview</h2>
    <div class="stat"><span>Total Source Files:</span> <strong>${metrics.totalFiles || 0}</strong></div>
    <div class="stat"><span>Total Lines of Code:</span> <strong>${metrics.totalLines || 0}</strong></div>
  </div>
</body>
</html>`;

    downloadFile(htmlContent, `${projectName}-interactive-audit.html`, 'text/html');
  };

  const handleDownloadJson = () => {
    downloadFile(JSON.stringify(result, null, 2), `${projectName}-analysis.json`, 'application/json');
  };

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold border border-slate-200 dark:border-slate-800 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-violet-600 hover:text-white dark:hover:bg-violet-600 dark:hover:text-white transition-all shadow-sm"
      >
        <Download className="w-3.5 h-3.5" />
        <span>Export Report</span>
        <ChevronDown className="w-3.5 h-3.5 ml-0.5" />
      </button>

      {open && (
        <div className="absolute right-0 mt-2 w-64 rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-2xl p-1.5 z-30 text-xs font-medium space-y-1 animate-in fade-in zoom-in-95 duration-100">
          {/* Priority AI Remediation Spec option */}
          <button
            onClick={() => {
              setOpen(false);
              onOpenRemediationModal?.();
            }}
            className="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl bg-violet-500/10 hover:bg-violet-500/20 text-violet-700 dark:text-violet-300 font-semibold transition-colors"
          >
            <Sparkles className="w-4 h-4 text-violet-500 shrink-0" />
            <div className="text-left">
              <div>AI Remediation Spec (.md)</div>
              <div className="text-[10px] text-violet-500/70 font-normal">Developer & LLM Prompt Spec</div>
            </div>
          </button>

          <button
            onClick={handleDownloadRemediationSpec}
            className="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-200 transition-colors"
          >
            <Bot className="w-4 h-4 text-cyan-500 shrink-0" />
            <span>Download REFACTOR_SPEC.md</span>
          </button>

          <div className="h-px bg-slate-200 dark:bg-slate-800 my-1" />

          <button
            onClick={handleDownloadMd}
            className="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-200 transition-colors"
          >
            <FileText className="w-4 h-4 text-slate-400 shrink-0" />
            <span>General Markdown Report (.md)</span>
          </button>

          <button
            onClick={handleDownloadHtml}
            className="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-200 transition-colors"
          >
            <FileCode className="w-4 h-4 text-emerald-500 shrink-0" />
            <span>Interactive HTML (.html)</span>
          </button>

          <button
            onClick={handleDownloadJson}
            className="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-200 transition-colors"
          >
            <Code2 className="w-4 h-4 text-amber-500 shrink-0" />
            <span>Raw Data Dump (.json)</span>
          </button>
        </div>
      )}
    </div>
  );
}
