// src/components/dashboard/DownloadButton.jsx
import React from 'react';
import { Download } from 'lucide-react';

/**
 * Generates and downloads a complete Markdown report.
 */
export default function DownloadButton({ result, projectName = 'codebase' }) {
  if (!result) return null;

  const handleDownload = () => {
    const { metrics = {}, requirements = { commands: [], dependencies: [] }, hld = '', lld = '', lineage = '' } = result;
    const now = new Date().toLocaleString();

    const lines = [
      `# Codebase Analysis Report`,
      `> Generated by Zero-LLM Codebase Scanner on ${now}`,
      '',
      '---',
      '',
      '## 📊 Metrics',
      '',
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Total Files | ${(metrics.totalFiles || 0).toLocaleString()} |`,
      `| Total Lines of Code | ${(metrics.totalLines || 0).toLocaleString()} |`,
      `| Languages Detected | ${Object.keys(metrics.byLanguage || {}).length} |`,
      '',
      '### Language Breakdown',
      '',
      '| Extension | Lines | % |',
      '|-----------|-------|---|',
      ...Object.entries(metrics.byLanguage || {})
        .sort(([,a],[,b]) => b-a)
        .map(([ext, lines]) => {
          const pct = metrics.totalLines > 0 ? Math.round((lines / metrics.totalLines) * 100) : 0;
          return `| \`${ext}\` | ${lines.toLocaleString()} | ${pct}% |`;
        }),
      '',
      '---',
      '',
      '## 🛠 Setup Requirements',
      '',
      '### Commands',
      '',
      ...(requirements.commands || []).map(cmd => `\`\`\`bash\n${cmd}\n\`\`\``),
      '',
      '### Dependencies',
      '',
      (requirements.dependencies || []).length > 0
        ? [
            '| Package | Version | Source |',
            '|---------|---------|--------|',
            ...requirements.dependencies.map(d => `| \`${d.name}\` | ${d.version} | ${d.source} |`)
          ].join('\n')
        : '_No dependency files detected._',
      '',
      '---',
      '',
      '## 🏗 High-Level Design (HLD)',
      '',
      '```mermaid',
      hld,
      '```',
      '',
      '---',
      '',
      '## 🔗 File Lineage (Dependency Graph)',
      '',
      '```mermaid',
      lineage,
      '```',
      '',
      '---',
      '',
      '## 🧩 Low-Level Design (LLD)',
      '',
      '```mermaid',
      lld,
      '```',
      '',
      '---',
      '',
      '_This report was generated deterministically — no AI APIs were used._',
    ];

    const content = lines.join('\n');
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName.replace(/[^a-z0-9]/gi, '-')}-analysis-report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold border border-slate-200 dark:border-slate-800 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-violet-600 hover:text-white dark:hover:bg-violet-600 dark:hover:text-white transition-all shadow-sm"
    >
      <Download className="w-3.5 h-3.5" />
      <span>Download Report (.md)</span>
    </button>
  );
}
